name: dist1
mean_aspect: 1
mean_n: 8
mean_r: 25
min_offset: 1
sd_aspect: 0.2
sd_n: 4
sd_r: 8
xdim: 250
ydim: 250
gutters:
- 10
- 10
mean_theta: .2
sd_theta: .1
n_dist:
- !!python/tuple
  - 1
  - 0.5
- !!python/tuple
  - 2
  - 0.25
- !!python/tuple
  - 3
  - 0.125
- !!python/tuple
  - 4
  - 0.125